apiVersion: apps/v1
kind: Deployment
metadata:
  name: alumnos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alumnos
  template:
    metadata:
      labels:
        app: alumnos
    spec:
      containers:
        - name: alumnos-container
          image: imgalumnos  # Asegúrate de que este sea el nombre de tu imagen Docker
          imagePullPolicy: Never
          ports:
            - containerPort: 8005
          env:
            - name: HOST_DB
              value: "10.2.1.11" # IP de tu base de datos (o nombre del servicio DB)
            - name: PORT_DB
              value: "3306"
            - name: USER_DB
              value: "root"
            - name: PASS_DB
              value: "root"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://10.2.1.11:3306/alumnoscursos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: DB_SECURITY_URL
              value: "jdbc:mysql://10.2.1.11:3306/springsecurity?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"  
