spring.application.name=33_microservicio_formacion_acceso_jwt
server.port=9005
server.servlet.context-path=/formacion

remote.url=http://servicio-alumnos/escuela/

remote.user=admin
remote.password=admin