spring.application.name=32_microservicio_formacion_acceso_basico
server.port=9005
server.servlet.context-path=/formacion

remote.url=http://localhost:8005/escuela

remote.user=admin
remote.password=admin